#pragma once

// Handedness by Pin - PA15
#define SPLIT_HAND_PIN A15
#define USB_SUSPEND_WAKEUP_DELAY 200
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

// Split USART Full-duplex 설정
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN A2
#define SERIAL_USART_RX_PIN A3
#define SERIAL_USART_DRIVER SD2  // PA2/PA3는 USART2
